# Generated by Django 5.1.8 on 2025-06-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_membership_and_foia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('resident', 'Resident')], max_length=20),
        ),
    ]
